export interface IFindMatches {
    match_id: number;
    barracks_status_dire: number;
    barracks_status_radiant: number;
    chat: number;
    cluster: number;
    cosmetics: number;
    dire_score: number;
    dire_team_id: number;
    draft_timings: number;
    duration: number;
    engine: number;
    first_blood_time: number;
    game_mode: number;
    human_players: number;
    leagueid: number;
    lobby_type: number;
    match_seq_num: number;
    negative_votes: number;
    objectives: number;
    picks_bans: number;
    positive_votes: number;
    radiant_gold_adv: number;
    radiant_score: number;
    radiant_team_id: number;
    radiant_win: boolean;
    radiant_xp_adv: number;
    skill: number;
    start_time: number;
    teamfights: number;
    tower_status_dire: number;
    tower_status_radiant: number;
    version: number;
    replay_salt: number;
    series_id: number;
    series_type: number;
    players: [
        {
            "match_id": number,
            "player_slot": number,
            "ability_targets": null,
            "ability_upgrades_arr": number[],
            "ability_uses": null,
            "account_id": number,
            "actions": null,
            "additional_units": null,
            "assists": number,
            "backpack_0": number,
            "backpack_1": number,
            "backpack_2": number,
            "backpack_3": null,
            "buyback_log": null,
            "camps_stacked": null,
            "connection_log": null,
            "creeps_stacked": null,
            "damage": number,
            "damage_inflictor": null,
            "damage_inflictor_received": null,
            "damage_taken": null,
            "damage_targets": null,
            "deaths": number,
            "denies": number,
            "dn_t": null,
            "firstblood_claimed": null,
            "gold": number,
            "gold_per_min": number,
            "gold_reasons": null,
            "gold_spent": number,
            "gold_t": null,
            "hero_damage": number,
            "hero_healing": number,
            "hero_hits": null,
            "hero_id": number,
            "item_0": number,
            "item_1": number,
            "item_2": number,
            "item_3": number,
            "item_4": number,
            "item_5": number,
            "item_neutral": number,
            "item_uses": null,
            "kill_streaks": null,
            "killed": number,
            "killed_by": null,
            "kills": number,
            "kills_log": null,
            "lane_pos": null,
            "last_hits": number,
            "leaver_status": number,
            "level": number,
            "lh_t": null,
            "life_state": null,
            "max_hero_hit": null,
            "multi_kills": null,
            "net_worth": number,
            "obs": number,
            "obs_left_log": null,
            "obs_log": null,
            "obs_placed": null,
            "party_id": number,
            "party_size": number,
            "performance_others": null,
            "permanent_buffs": [],
            "pings": number,
            "pred_vict": null,
            "purchase": null,
            "purchase_log": null,
            "randomed": null,
            "repicked": null,
            "roshans_killed": number,
            "rune_pickups": null,
            "runes": number,
            "runes_log": null,
            "sen": null,
            "sen_left_log": null,
            "sen_log": null,
            "sen_placed": null,
            "stuns": number,
            "teamfight_participation": null,
            "times": null,
            "tower_damage": number,
            "towers_killed": null,
            "xp_per_min": number,
            "xp_reasons": null,
            "xp_t": null,
            "radiant_win": false,
            "start_time": number,
            "duration": number,
            "cluster": number,
            "lobby_type": number,
            "game_mode": number,
            "is_contributor": boolean,
            "patch": number,
            "region": number,
            "isRadiant": boolean,
            "win": number,
            "lose": number,
            "total_gold": number,
            "total_xp": number,
            "kills_per_min": number,
            "kda": number,
            "abandons": number,
            "rank_tier": null,
            "is_subscriber": boolean,
            personaname: string;
            "cosmetics": [],
            "benchmarks": []
        }
    ]
    patch: number;
    region: number;
    replay_url: string;
}
